#pragma once

#include "NiShaderDescBase.hpp"

class NiShaderAttributeDesc : public NiShaderDescBase {
public:
	enum Flags {
		ATTRIB_FLAGS_NONE	= 0,
		ATTRIB_FLAGS_RANGED = 1,
		ATTRIB_FLAGS_HIDDEN = 2,
	};

	enum AttributeType {
		ATTRIB_TYPE_UNDEFINED	= 0,
		ATTRIB_TYPE_BOOL		= 1,
		ATTRIB_TYPE_STRING		= 2,
		ATTRIB_TYPE_UNSIGNEDINT = 3,
		ATTRIB_TYPE_FLOAT		= 4,
		ATTRIB_TYPE_POINT2		= 5,
		ATTRIB_TYPE_POINT3		= 6,
		ATTRIB_TYPE_POINT4		= 7,
		ATTRIB_TYPE_MATRIX3		= 8,
		ATTRIB_TYPE_MATRIX4		= 9,
		ATTRIB_TYPE_COLOR		= 10,
		ATTRIB_TYPE_TEXTURE		= 11,
		ATTRIB_TYPE_FLOAT8		= 12,
		ATTRIB_TYPE_FLOAT12		= 13,
		ATTRIB_TYPE_ARRAY		= 14,
		ATTRIB_TYPE_COUNT,
	};

	enum ObjectType {
		OT_UNDEFINED					= 0,
		OT_EFFECT_GENERALLIGHT			= 1,
		OT_EFFECT_POINTLIGHT			= 2,
		OT_EFFECT_DIRECTIONALLIGHT		= 3,
		OT_EFFECT_SPOTLIGHT				= 4,
		OT_EFFECT_ENVIRONMENTMAP		= 5,
		OT_EFFECT_PROJECTEDSHADOWMAP	= 6,
		OT_EFFECT_PROJECTEDLIGHTMAP		= 7,
		OT_EFFECT_FOGMAP				= 8,
		OT_COUNT
	};
};