set FXC="C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\fxc.exe"

if not exist package\Shaders\Loose mkdir package\Shaders\Loose
if not exist package\Shaders\Loose\SSS mkdir package\Shaders\Loose\SSS

set SHADER_FILE=shaders\SkinTemplate.hlsl

%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /Fo "package\shaders\loose\SKIN2008.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DSKIN /Fo "package\shaders\loose\SKIN2009.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2010.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DPROJ_SHADOW /DSKIN /Fo "package\shaders\loose\SKIN2011.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /Fo "package\shaders\loose\SKIN2012.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /DSKIN /Fo "package\shaders\loose\SKIN2013.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2014.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /DPROJ_SHADOW /DSKIN /Fo "package\shaders\loose\SKIN2015.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /Fo "package\shaders\loose\SKIN2000.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DSKIN /Fo "package\shaders\loose\SKIN2001.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2002.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DPROJ_SHADOW /DSKIN /Fo "package\shaders\loose\SKIN2003.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /Fo "package\shaders\loose\SKIN2004.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DSKIN /Fo "package\shaders\loose\SKIN2005.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2006.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DPROJ_SHADOW /DSKIN /Fo "package\shaders\loose\SKIN2007.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=9 /Fo "package\shaders\loose\SKIN2020.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=9 /DSKIN /Fo "package\shaders\loose\SKIN2021.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=4 /Fo "package\shaders\loose\SKIN2022.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=4 /DSKIN /Fo "package\shaders\loose\SKIN2023.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=4 /DSPECULAR /Fo "package\shaders\loose\SKIN2024.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=4 /DSPECULAR /DSKIN /Fo "package\shaders\loose\SKIN2025.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DDIFFUSE /Fo "package\shaders\loose\SKIN2016.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=2 /DDIFFUSE /DSKIN /Fo "package\shaders\loose\SKIN2017.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /DDIFFUSE /Fo "package\shaders\loose\SKIN2018.vso" "%SHADER_FILE%"
%FXC% /T vs_3_0 /E main /DVS /DLIGHTS=3 /DDIFFUSE /DSKIN /Fo "package\shaders\loose\SKIN2019.vso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=2 /DONLY_LIGHT /Fo "package\shaders\loose\SKIN2004.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=2 /DPROJ_SHADOW /DONLY_LIGHT /Fo "package\shaders\loose\SKIN2005.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=3 /DONLY_LIGHT /Fo "package\shaders\loose\SKIN2006.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=3 /DPROJ_SHADOW /DONLY_LIGHT /Fo "package\shaders\loose\SKIN2007.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /Fo "package\shaders\loose\SKIN2000.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2001.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=2 /Fo "package\shaders\loose\SKIN2002.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=2 /DPROJ_SHADOW /Fo "package\shaders\loose\SKIN2003.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=9 /Fo "package\shaders\loose\SKIN2010.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=4 /Fo "package\shaders\loose\SKIN2011.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=4 /DSPECULAR /Fo "package\shaders\loose\SKIN2012.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=2 /DDIFFUSE /Fo "package\shaders\loose\SKIN2008.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /DPS /DLIGHTS=3 /DDIFFUSE /Fo "package\shaders\loose\SKIN2009.pso" "%SHADER_FILE%"

set SHADER_FILE=shaders\LUT.hlsl
%FXC% /T ps_3_0 /E main /DSCATTER_PROFILE /Fo "package\shaders\loose\SSS\LINEAR_PROFILE.pso" "%SHADER_FILE%"
%FXC% /T ps_3_0 /E main /Fo "package\shaders\loose\SSS\LUT.pso" "%SHADER_FILE%"
